/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0uDydX17XSP
 */
import { Button } from "./button"
import { Input } from "./input"

export function SignUpForm() {
  return (
    (<aside
      className="fixed inset-0 z-50 flex items-center justify-center px-4 text-center bg-black bg-opacity-50">
      <div
        className="mx-auto w-full max-w-sm overflow-hidden rounded-xl shadow-lg bg-white dark:bg-gray-900">
        <Button className="absolute top-2 right-2 -mt-1" size="icon" variant="ghost">
          <XIcon className="w-4 h-4" />
          <span className="sr-only">Close</span>
        </Button>
        <div className="p-8 space-y-6">
          <div className="space-y-2 text-center">
            <h2 className="text-2xl font-bold">Sign Up</h2>
            <p className="text-gray-500 dark:text-gray-400">Enter your information to create an account</p>
          </div>
          <div className="space-y-4">
            <div className="space-y-2">
              <Input id="name" placeholder="Name" />
            </div>
            <div className="space-y-2">
              <Input id="email" placeholder="Email" type="email" />
            </div>
            <div className="space-y-2">
              <Input id="password" placeholder="Password" type="password" />
            </div>
            <Button className="w-full">Sign Up</Button>
          </div>
        </div>
      </div>
    </aside>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
